-- AEGIS baseline schema (squashed).
-- Consolidates the historical 001..027 migrations into one file for fresh
-- installs. Generated by applying all 27 migrations to a clean pgvector/pg16
-- database and dumping the resulting schema (pg_dump --schema-only), then:
--   * stripped pg_dump/psql preamble (SET, \restrict, search_path) so the
--     asyncpg runner can execute it as a single statement batch;
--   * dropped the dead knowledge_source_quality.review_confidence column;
--   * added the infra registry + resources.infra_id link (new in this cut).
-- Fresh installs run only this file. Existing deployments keep their applied
-- 001..027 rows and never see it (runner tracks by filename).


-- Name: maou; Type: SCHEMA; Schema: -; Owner: -

CREATE SCHEMA maou;

-- Name: pandoras_actor; Type: SCHEMA; Schema: -; Owner: -

CREATE SCHEMA pandoras_actor;

-- Name: vector; Type: EXTENSION; Schema: -; Owner: -

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';

-- Name: receipt_email; Type: TABLE; Schema: maou; Owner: -

CREATE TABLE maou.receipt_email (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    message_id text NOT NULL,
    account text NOT NULL,
    sender text NOT NULL,
    subject text,
    received_at timestamp with time zone NOT NULL,
    charge_id uuid,
    parsed jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: recurring_charge; Type: TABLE; Schema: maou; Owner: -

CREATE TABLE maou.recurring_charge (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account text NOT NULL,
    sender_label text NOT NULL,
    vendor_name text NOT NULL,
    category text DEFAULT 'other'::text NOT NULL,
    amount_cents integer NOT NULL,
    currency text NOT NULL,
    monthly_inr_equivalent numeric DEFAULT 0 NOT NULL,
    cadence text DEFAULT 'unknown'::text NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    next_due_at timestamp with time zone,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: renewal_alert; Type: TABLE; Schema: maou; Owner: -

CREATE TABLE maou.renewal_alert (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    charge_id uuid NOT NULL,
    threshold_days integer NOT NULL,
    fired_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_notified_at timestamp with time zone
);

-- Name: subscription_digest; Type: TABLE; Schema: maou; Owner: -

CREATE TABLE maou.subscription_digest (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    summary jsonb NOT NULL,
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: backup_health; Type: TABLE; Schema: pandoras_actor; Owner: -

CREATE TABLE pandoras_actor.backup_health (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    backup_set text NOT NULL,
    last_backup_at timestamp with time zone,
    size_bytes bigint,
    size_delta_pct numeric,
    restore_drill_at timestamp with time zone,
    restore_drill_ok boolean,
    restore_drill_ms integer,
    notes text,
    checked_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: cert_expiry; Type: TABLE; Schema: pandoras_actor; Owner: -

CREATE TABLE pandoras_actor.cert_expiry (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    domain text NOT NULL,
    cert_serial text NOT NULL,
    not_after timestamp with time zone NOT NULL,
    days_until_expiry integer NOT NULL,
    last_alert_threshold integer,
    checked_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: homelab_drift; Type: TABLE; Schema: pandoras_actor; Owner: -

CREATE TABLE pandoras_actor.homelab_drift (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    service_name text NOT NULL,
    stack_name text NOT NULL,
    drift_type text NOT NULL,
    expected jsonb NOT NULL,
    actual jsonb NOT NULL,
    severity text NOT NULL,
    alert_key text NOT NULL,
    detected_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone
);

-- Name: schedule_health; Type: TABLE; Schema: pandoras_actor; Owner: -

CREATE TABLE pandoras_actor.schedule_health (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source text NOT NULL,
    schedule_name text NOT NULL,
    expected_status text NOT NULL,
    actual_status text NOT NULL,
    last_run_at timestamp with time zone,
    last_run_ok boolean,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    alert_key text,
    checked_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: activities; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.activities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    slug text NOT NULL,
    workflow_type text NOT NULL,
    agent_id text NOT NULL,
    schedule_cron text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: agent_memory; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.agent_memory (
    id bigint NOT NULL,
    agent_id text NOT NULL,
    content text NOT NULL,
    importance real DEFAULT 0.5 NOT NULL,
    source text DEFAULT 'correction'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: agent_memory_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.agent_memory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: agent_memory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.agent_memory_id_seq OWNED BY public.agent_memory.id;

-- Name: agents; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.agents (
    id text NOT NULL,
    name text NOT NULL,
    role text NOT NULL,
    system_prompt_path text NOT NULL,
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_tier text DEFAULT 'balanced'::text NOT NULL,
    interaction_timeout_default text DEFAULT 'archive'::text NOT NULL,
    telegram_topic_id integer,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    slack_channel_id text,
    elevenlabs_voice_id text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    soul text,
    operating_notes text,
    user_context text
);

-- Name: COLUMN agents.slack_channel_id; Type: COMMENT; Schema: public; Owner: -

COMMENT ON COLUMN public.agents.slack_channel_id IS 'Slack channel id for this agent (active when AEGIS_CHANNEL=slack)';

-- Name: COLUMN agents.elevenlabs_voice_id; Type: COMMENT; Schema: public; Owner: -

COMMENT ON COLUMN public.agents.elevenlabs_voice_id IS 'ElevenLabs voice id for this agent''s TTS voice notes (active when AEGIS_TTS_ENABLED=true)';

-- Name: alert_dedup_index; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.alert_dedup_index (
    signature text NOT NULL,
    task_id text NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    occurrence_count integer DEFAULT 1 NOT NULL
);

-- Name: alert_mutes; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.alert_mutes (
    mute_key text NOT NULL,
    muted_until timestamp with time zone NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by text DEFAULT ''::text NOT NULL
);

-- Name: audit_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.audit_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    actor text NOT NULL,
    action text NOT NULL,
    target_type text,
    target_id text,
    details jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: channels; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.channels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind text NOT NULL,
    identifier text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: chat_history; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_history (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    thread_id text NOT NULL,
    agent_id text NOT NULL,
    role text NOT NULL,
    content text,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: chat_tool_calls; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_tool_calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id text NOT NULL,
    tool_name text NOT NULL,
    args jsonb,
    result jsonb,
    status text NOT NULL,
    latency_ms integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: connector_calls; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.connector_calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id text,
    workflow_run_id text,
    connector text NOT NULL,
    action text NOT NULL,
    status text NOT NULL,
    latency_ms integer,
    external_ref text,
    error text,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: gtd_clarify_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.gtd_clarify_log (
    id bigint NOT NULL,
    todoist_task_id text NOT NULL,
    pass integer DEFAULT 1 NOT NULL,
    source_tag text,
    classification text NOT NULL,
    confidence real NOT NULL,
    assignee text,
    contexts text[] DEFAULT '{}'::text[] NOT NULL,
    reason text,
    user_hint text,
    llm_model text NOT NULL,
    prompt_tokens integer,
    completion_tokens integer,
    latency_ms integer,
    applied boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: gtd_clarify_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.gtd_clarify_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: gtd_clarify_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.gtd_clarify_log_id_seq OWNED BY public.gtd_clarify_log.id;

-- Name: ingest_idempotency; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.ingest_idempotency (
    source_type text NOT NULL,
    external_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: interactions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.interactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    flow_run_id text NOT NULL,
    agent_id text NOT NULL,
    kind text NOT NULL,
    origin text NOT NULL,
    prompt text NOT NULL,
    options jsonb,
    status text DEFAULT 'pending'::text NOT NULL,
    response jsonb,
    timeout_at timestamp with time zone,
    timeout_policy text DEFAULT 'archive'::text NOT NULL,
    telegram_message_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    delivery_ref jsonb
);

-- Name: COLUMN interactions.delivery_ref; Type: COMMENT; Schema: public; Owner: -

COMMENT ON COLUMN public.interactions.delivery_ref IS 'Channel-neutral message ref {adapter, ...} for edit/delete (slack: {adapter,channel,ts}; telegram: {adapter,chat_id,message_id})';

-- Name: knowledge_chunks; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.knowledge_chunks (
    id bigint NOT NULL,
    content_id text NOT NULL,
    chunk_index integer DEFAULT 0 NOT NULL,
    chunk_text text NOT NULL,
    embedding public.vector(768)
);

-- Name: knowledge_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.knowledge_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: knowledge_chunks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.knowledge_chunks_id_seq OWNED BY public.knowledge_chunks.id;

-- Name: knowledge_content; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.knowledge_content (
    content_id text NOT NULL,
    url text,
    title text,
    source_type text,
    summary text,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: knowledge_injection_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.knowledge_injection_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id text NOT NULL,
    thread_id text,
    workflow_run_id text,
    source text NOT NULL,
    content_ids text[] DEFAULT '{}'::text[] NOT NULL,
    triples_used jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: knowledge_source_quality; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.knowledge_source_quality (
    source_type text NOT NULL,
    auto_confidence numeric DEFAULT 0.7 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: llm_calls; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.llm_calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id text,
    workflow_run_id text,
    model text NOT NULL,
    purpose text,
    input_tokens integer,
    output_tokens integer,
    latency_ms integer,
    status text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: notification_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.notification_log (
    id bigint NOT NULL,
    agent_id text,
    log_event text,
    sent boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: notification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.notification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: notification_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.notification_log_id_seq OWNED BY public.notification_log.id;

-- Name: pending_prs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.pending_prs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    interaction_id uuid,
    alert_fingerprint text NOT NULL,
    repo text NOT NULL,
    branch text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    diff text DEFAULT ''::text NOT NULL,
    kimi_session_id text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    pr_url text DEFAULT ''::text NOT NULL,
    CONSTRAINT pending_prs_status_valid CHECK ((status = ANY (ARRAY['pending'::text, 'opened'::text, 'closed'::text, 'discarded'::text, 'failed'::text])))
);

-- Name: resources; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.resources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind text NOT NULL,
    slug text NOT NULL,
    title text NOT NULL,
    content text,
    url text,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: review_digest_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.review_digest_log (
    id bigint NOT NULL,
    review_kind text NOT NULL,
    counts jsonb DEFAULT '{}'::jsonb NOT NULL,
    preview text,
    interaction_id text,
    user_choice text,
    acknowledged boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    acknowledged_at timestamp with time zone
);

-- Name: review_digest_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.review_digest_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: review_digest_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.review_digest_log_id_seq OWNED BY public.review_digest_log.id;

-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.schema_migrations (
    filename text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: settings; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_capture_idempotency; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_capture_idempotency (
    source_tag text NOT NULL,
    external_id text NOT NULL,
    todoist_task_ref text,
    captured_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_labels; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_labels (
    id text NOT NULL,
    name text NOT NULL,
    color text,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL
);

-- Name: todoist_notes; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_notes (
    id text NOT NULL,
    item_id text NOT NULL,
    content text NOT NULL,
    posted_uid text,
    posted_at timestamp with time zone NOT NULL,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_outbox; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_outbox (
    id bigint NOT NULL,
    temp_id text NOT NULL,
    command jsonb NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp with time zone,
    status text DEFAULT 'pending'::text NOT NULL,
    committed_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_outbox_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.todoist_outbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: todoist_outbox_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.todoist_outbox_id_seq OWNED BY public.todoist_outbox.id;

-- Name: todoist_projects; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_projects (
    id text NOT NULL,
    parent_id text,
    name text NOT NULL,
    is_managed boolean DEFAULT false NOT NULL,
    is_archived boolean DEFAULT false NOT NULL,
    order_idx integer,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_sync_state; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_sync_state (
    key text NOT NULL,
    sync_token text NOT NULL,
    last_full_sync_at timestamp with time zone,
    last_incremental_at timestamp with time zone
);

-- Name: todoist_tasks; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_tasks (
    id text NOT NULL,
    project_id text,
    parent_id text,
    content text NOT NULL,
    description text,
    due_date date,
    priority smallint,
    labels text[] DEFAULT '{}'::text[] NOT NULL,
    is_completed boolean DEFAULT false NOT NULL,
    completed_at timestamp with time zone,
    assignee_label text,
    source_tag text,
    raw jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_clarified_at timestamp with time zone,
    last_note_at timestamp with time zone
);

-- Name: todoist_webhook_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.todoist_webhook_events (
    id bigint NOT NULL,
    event_name text NOT NULL,
    event_data jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: todoist_webhook_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.todoist_webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: todoist_webhook_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.todoist_webhook_events_id_seq OWNED BY public.todoist_webhook_events.id;

-- Name: triage_accuracy; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.triage_accuracy (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email_id text NOT NULL,
    predicted text NOT NULL,
    actual text,
    corrected_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: triage_state; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.triage_state (
    email_addr text NOT NULL,
    state text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: workflow_runs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.workflow_runs (
    run_id text NOT NULL,
    workflow_id text NOT NULL,
    workflow_type text NOT NULL,
    agent_id text,
    parent_run_id text,
    status text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    duration_ms integer,
    error text,
    input_summary jsonb,
    result_summary jsonb,
    todoist_task_ref text
);

-- Name: agent_memory id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.agent_memory ALTER COLUMN id SET DEFAULT nextval('public.agent_memory_id_seq'::regclass);

-- Name: gtd_clarify_log id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.gtd_clarify_log ALTER COLUMN id SET DEFAULT nextval('public.gtd_clarify_log_id_seq'::regclass);

-- Name: knowledge_chunks id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_chunks ALTER COLUMN id SET DEFAULT nextval('public.knowledge_chunks_id_seq'::regclass);

-- Name: notification_log id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.notification_log ALTER COLUMN id SET DEFAULT nextval('public.notification_log_id_seq'::regclass);

-- Name: review_digest_log id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.review_digest_log ALTER COLUMN id SET DEFAULT nextval('public.review_digest_log_id_seq'::regclass);

-- Name: todoist_outbox id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_outbox ALTER COLUMN id SET DEFAULT nextval('public.todoist_outbox_id_seq'::regclass);

-- Name: todoist_webhook_events id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_webhook_events ALTER COLUMN id SET DEFAULT nextval('public.todoist_webhook_events_id_seq'::regclass);

-- Name: receipt_email receipt_email_message_id_key; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.receipt_email
    ADD CONSTRAINT receipt_email_message_id_key UNIQUE (message_id);

-- Name: receipt_email receipt_email_pkey; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.receipt_email
    ADD CONSTRAINT receipt_email_pkey PRIMARY KEY (id);

-- Name: recurring_charge recurring_charge_account_sender_label_amount_cents_currency_key; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.recurring_charge
    ADD CONSTRAINT recurring_charge_account_sender_label_amount_cents_currency_key UNIQUE (account, sender_label, amount_cents, currency);

-- Name: recurring_charge recurring_charge_pkey; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.recurring_charge
    ADD CONSTRAINT recurring_charge_pkey PRIMARY KEY (id);

-- Name: renewal_alert renewal_alert_pkey; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.renewal_alert
    ADD CONSTRAINT renewal_alert_pkey PRIMARY KEY (id);

-- Name: subscription_digest subscription_digest_period_start_period_end_key; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.subscription_digest
    ADD CONSTRAINT subscription_digest_period_start_period_end_key UNIQUE (period_start, period_end);

-- Name: subscription_digest subscription_digest_pkey; Type: CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.subscription_digest
    ADD CONSTRAINT subscription_digest_pkey PRIMARY KEY (id);

-- Name: backup_health backup_health_pkey; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.backup_health
    ADD CONSTRAINT backup_health_pkey PRIMARY KEY (id);

-- Name: cert_expiry cert_expiry_domain_cert_serial_key; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.cert_expiry
    ADD CONSTRAINT cert_expiry_domain_cert_serial_key UNIQUE (domain, cert_serial);

-- Name: cert_expiry cert_expiry_pkey; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.cert_expiry
    ADD CONSTRAINT cert_expiry_pkey PRIMARY KEY (id);

-- Name: homelab_drift homelab_drift_pkey; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.homelab_drift
    ADD CONSTRAINT homelab_drift_pkey PRIMARY KEY (id);

-- Name: schedule_health schedule_health_pkey; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.schedule_health
    ADD CONSTRAINT schedule_health_pkey PRIMARY KEY (id);

-- Name: schedule_health schedule_health_source_schedule_name_key; Type: CONSTRAINT; Schema: pandoras_actor; Owner: -

ALTER TABLE ONLY pandoras_actor.schedule_health
    ADD CONSTRAINT schedule_health_source_schedule_name_key UNIQUE (source, schedule_name);

-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);

-- Name: activities activities_slug_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_slug_key UNIQUE (slug);

-- Name: agent_memory agent_memory_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.agent_memory
    ADD CONSTRAINT agent_memory_pkey PRIMARY KEY (id);

-- Name: agents agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (id);

-- Name: alert_dedup_index alert_dedup_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.alert_dedup_index
    ADD CONSTRAINT alert_dedup_index_pkey PRIMARY KEY (signature);

-- Name: alert_mutes alert_mutes_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.alert_mutes
    ADD CONSTRAINT alert_mutes_pkey PRIMARY KEY (mute_key);

-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- Name: channels channels_kind_identifier_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channels_kind_identifier_key UNIQUE (kind, identifier);

-- Name: channels channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channels_pkey PRIMARY KEY (id);

-- Name: chat_history chat_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_history
    ADD CONSTRAINT chat_history_pkey PRIMARY KEY (id);

-- Name: chat_tool_calls chat_tool_calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_tool_calls
    ADD CONSTRAINT chat_tool_calls_pkey PRIMARY KEY (id);

-- Name: connector_calls connector_calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.connector_calls
    ADD CONSTRAINT connector_calls_pkey PRIMARY KEY (id);

-- Name: gtd_clarify_log gtd_clarify_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.gtd_clarify_log
    ADD CONSTRAINT gtd_clarify_log_pkey PRIMARY KEY (id);

-- Name: ingest_idempotency ingest_idempotency_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.ingest_idempotency
    ADD CONSTRAINT ingest_idempotency_pkey PRIMARY KEY (source_type, external_id);

-- Name: interactions interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT interactions_pkey PRIMARY KEY (id);

-- Name: knowledge_chunks knowledge_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id);

-- Name: knowledge_content knowledge_content_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_content
    ADD CONSTRAINT knowledge_content_pkey PRIMARY KEY (content_id);

-- Name: knowledge_injection_log knowledge_injection_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_injection_log
    ADD CONSTRAINT knowledge_injection_log_pkey PRIMARY KEY (id);

-- Name: knowledge_source_quality knowledge_source_quality_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_source_quality
    ADD CONSTRAINT knowledge_source_quality_pkey PRIMARY KEY (source_type);

-- Name: llm_calls llm_calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.llm_calls
    ADD CONSTRAINT llm_calls_pkey PRIMARY KEY (id);

-- Name: notification_log notification_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.notification_log
    ADD CONSTRAINT notification_log_pkey PRIMARY KEY (id);

-- Name: pending_prs pending_prs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pending_prs
    ADD CONSTRAINT pending_prs_pkey PRIMARY KEY (id);

-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);

-- Name: resources resources_slug_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_slug_key UNIQUE (slug);

-- Name: review_digest_log review_digest_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.review_digest_log
    ADD CONSTRAINT review_digest_log_pkey PRIMARY KEY (id);

-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);

-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);

-- Name: todoist_capture_idempotency todoist_capture_idempotency_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_capture_idempotency
    ADD CONSTRAINT todoist_capture_idempotency_pkey PRIMARY KEY (source_tag, external_id);

-- Name: todoist_labels todoist_labels_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_labels
    ADD CONSTRAINT todoist_labels_pkey PRIMARY KEY (id);

-- Name: todoist_notes todoist_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_notes
    ADD CONSTRAINT todoist_notes_pkey PRIMARY KEY (id);

-- Name: todoist_outbox todoist_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_outbox
    ADD CONSTRAINT todoist_outbox_pkey PRIMARY KEY (id);

-- Name: todoist_outbox todoist_outbox_temp_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_outbox
    ADD CONSTRAINT todoist_outbox_temp_id_key UNIQUE (temp_id);

-- Name: todoist_projects todoist_projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_projects
    ADD CONSTRAINT todoist_projects_pkey PRIMARY KEY (id);

-- Name: todoist_sync_state todoist_sync_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_sync_state
    ADD CONSTRAINT todoist_sync_state_pkey PRIMARY KEY (key);

-- Name: todoist_tasks todoist_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_tasks
    ADD CONSTRAINT todoist_tasks_pkey PRIMARY KEY (id);

-- Name: todoist_webhook_events todoist_webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_webhook_events
    ADD CONSTRAINT todoist_webhook_events_pkey PRIMARY KEY (id);

-- Name: triage_accuracy triage_accuracy_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.triage_accuracy
    ADD CONSTRAINT triage_accuracy_pkey PRIMARY KEY (id);

-- Name: triage_state triage_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.triage_state
    ADD CONSTRAINT triage_state_pkey PRIMARY KEY (email_addr);

-- Name: workflow_runs workflow_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.workflow_runs
    ADD CONSTRAINT workflow_runs_pkey PRIMARY KEY (run_id);

-- Name: receipt_email_charge_id_idx; Type: INDEX; Schema: maou; Owner: -

CREATE INDEX receipt_email_charge_id_idx ON maou.receipt_email USING btree (charge_id);

-- Name: renewal_alert_daily_dedup; Type: INDEX; Schema: maou; Owner: -

CREATE UNIQUE INDEX renewal_alert_daily_dedup ON maou.renewal_alert USING btree (charge_id, threshold_days, (((fired_at AT TIME ZONE 'UTC'::text))::date));

-- Name: renewal_alert_notify_lookup_idx; Type: INDEX; Schema: maou; Owner: -

CREATE INDEX renewal_alert_notify_lookup_idx ON maou.renewal_alert USING btree (charge_id, threshold_days, last_notified_at);

-- Name: backup_health_set_checked_idx; Type: INDEX; Schema: pandoras_actor; Owner: -

CREATE INDEX backup_health_set_checked_idx ON pandoras_actor.backup_health USING btree (backup_set, checked_at DESC);

-- Name: cert_expiry_domain_checked_idx; Type: INDEX; Schema: pandoras_actor; Owner: -

CREATE INDEX cert_expiry_domain_checked_idx ON pandoras_actor.cert_expiry USING btree (domain, checked_at DESC);

-- Name: homelab_drift_open_alert_key_idx; Type: INDEX; Schema: pandoras_actor; Owner: -

CREATE UNIQUE INDEX homelab_drift_open_alert_key_idx ON pandoras_actor.homelab_drift USING btree (alert_key) WHERE (resolved_at IS NULL);

-- Name: homelab_drift_service_detected_at_idx; Type: INDEX; Schema: pandoras_actor; Owner: -

CREATE INDEX homelab_drift_service_detected_at_idx ON pandoras_actor.homelab_drift USING btree (service_name, detected_at DESC);

-- Name: activities_agent_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX activities_agent_id_idx ON public.activities USING btree (agent_id) WHERE active;

-- Name: agent_memory_agent_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX agent_memory_agent_idx ON public.agent_memory USING btree (agent_id, importance DESC, created_at DESC);

-- Name: alert_dedup_index_task_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX alert_dedup_index_task_id_idx ON public.alert_dedup_index USING btree (task_id);

-- Name: alert_mutes_until_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX alert_mutes_until_idx ON public.alert_mutes USING btree (muted_until);

-- Name: audit_log_actor_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX audit_log_actor_created_at_idx ON public.audit_log USING btree (actor, created_at DESC);

-- Name: audit_log_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX audit_log_created_at_idx ON public.audit_log USING btree (created_at DESC);

-- Name: chat_history_agent_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_history_agent_id_created_at_idx ON public.chat_history USING btree (agent_id, created_at DESC);

-- Name: chat_history_thread_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_history_thread_id_created_at_idx ON public.chat_history USING btree (thread_id, created_at);

-- Name: chat_tool_calls_agent_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_tool_calls_agent_id_created_at_idx ON public.chat_tool_calls USING btree (agent_id, created_at DESC);

-- Name: chat_tool_calls_tool_name_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_tool_calls_tool_name_created_at_idx ON public.chat_tool_calls USING btree (tool_name, created_at DESC);

-- Name: connector_calls_agent_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX connector_calls_agent_id_created_at_idx ON public.connector_calls USING btree (agent_id, created_at DESC);

-- Name: connector_calls_connector_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX connector_calls_connector_created_at_idx ON public.connector_calls USING btree (connector, created_at DESC);

-- Name: gtd_clarify_log_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX gtd_clarify_log_created_at_idx ON public.gtd_clarify_log USING btree (created_at);

-- Name: gtd_clarify_log_task_pass_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX gtd_clarify_log_task_pass_idx ON public.gtd_clarify_log USING btree (todoist_task_id, pass);

-- Name: idx_todoist_tasks_labels_gin_open; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_todoist_tasks_labels_gin_open ON public.todoist_tasks USING gin (labels) WHERE (NOT is_completed);

-- Name: interactions_agent_id_status_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX interactions_agent_id_status_created_at_idx ON public.interactions USING btree (agent_id, status, created_at DESC);

-- Name: interactions_flow_run_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX interactions_flow_run_id_idx ON public.interactions USING btree (flow_run_id) WHERE (status = 'pending'::text);

-- Name: interactions_metadata_source_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX interactions_metadata_source_idx ON public.interactions USING btree (((metadata ->> 'source'::text))) WHERE (status = 'pending'::text);

-- Name: interactions_origin_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX interactions_origin_created_at_idx ON public.interactions USING btree (origin, created_at DESC);

-- Name: knowledge_chunks_content_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX knowledge_chunks_content_id_idx ON public.knowledge_chunks USING btree (content_id);

-- Name: knowledge_chunks_embedding_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX knowledge_chunks_embedding_idx ON public.knowledge_chunks USING hnsw (embedding public.vector_cosine_ops);

-- Name: knowledge_content_source_type_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX knowledge_content_source_type_idx ON public.knowledge_content USING btree (source_type, ingested_at DESC);

-- Name: knowledge_injection_log_agent_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX knowledge_injection_log_agent_id_created_at_idx ON public.knowledge_injection_log USING btree (agent_id, created_at DESC);

-- Name: llm_calls_agent_id_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX llm_calls_agent_id_created_at_idx ON public.llm_calls USING btree (agent_id, created_at DESC);

-- Name: llm_calls_workflow_run_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX llm_calls_workflow_run_id_idx ON public.llm_calls USING btree (workflow_run_id);

-- Name: notification_log_day_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX notification_log_day_idx ON public.notification_log USING btree (created_at DESC);

-- Name: pending_prs_status_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX pending_prs_status_idx ON public.pending_prs USING btree (status, created_at);

-- Name: resources_tags_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX resources_tags_idx ON public.resources USING gin (tags);

-- Name: resources_vercel_github_repo_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX resources_vercel_github_repo_idx ON public.resources USING btree (((metadata ->> 'github_repo'::text))) WHERE (kind = 'vercel_project'::text);

-- Name: review_digest_log_interaction_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX review_digest_log_interaction_idx ON public.review_digest_log USING btree (interaction_id) WHERE (interaction_id IS NOT NULL);

-- Name: review_digest_log_kind_created_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX review_digest_log_kind_created_idx ON public.review_digest_log USING btree (review_kind, created_at DESC);

-- Name: todoist_capture_idempotency_captured_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_capture_idempotency_captured_at_idx ON public.todoist_capture_idempotency USING btree (captured_at);

-- Name: todoist_notes_item_posted_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_notes_item_posted_idx ON public.todoist_notes USING btree (item_id, posted_at DESC);

-- Name: todoist_outbox_status_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_outbox_status_created_at_idx ON public.todoist_outbox USING btree (status, created_at);

-- Name: todoist_projects_is_managed_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_projects_is_managed_idx ON public.todoist_projects USING btree (is_managed) WHERE is_managed;

-- Name: todoist_projects_parent_id_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_projects_parent_id_idx ON public.todoist_projects USING btree (parent_id);

-- Name: todoist_tasks_assignee_label_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_assignee_label_idx ON public.todoist_tasks USING btree (assignee_label) WHERE (NOT is_completed);

-- Name: todoist_tasks_due_date_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_due_date_idx ON public.todoist_tasks USING btree (due_date) WHERE (NOT is_completed);

-- Name: todoist_tasks_note_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_note_at_idx ON public.todoist_tasks USING btree (project_id, last_note_at) WHERE (last_note_at IS NOT NULL);

-- Name: todoist_tasks_project_id_is_completed_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_project_id_is_completed_idx ON public.todoist_tasks USING btree (project_id, is_completed);

-- Name: todoist_tasks_source_tag_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_source_tag_idx ON public.todoist_tasks USING btree (source_tag);

-- Name: todoist_tasks_unclarified_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_tasks_unclarified_idx ON public.todoist_tasks USING btree (last_clarified_at) WHERE (last_clarified_at IS NULL);

-- Name: todoist_webhook_events_event_name_received_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX todoist_webhook_events_event_name_received_at_idx ON public.todoist_webhook_events USING btree (event_name, received_at DESC);

-- Name: triage_accuracy_created_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX triage_accuracy_created_at_idx ON public.triage_accuracy USING btree (created_at DESC);

-- Name: workflow_runs_agent_id_started_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX workflow_runs_agent_id_started_at_idx ON public.workflow_runs USING btree (agent_id, started_at DESC);

-- Name: workflow_runs_status_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX workflow_runs_status_idx ON public.workflow_runs USING btree (status) WHERE (status = 'running'::text);

-- Name: workflow_runs_todoist_task_ref_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX workflow_runs_todoist_task_ref_idx ON public.workflow_runs USING btree (todoist_task_ref) WHERE (todoist_task_ref IS NOT NULL);

-- Name: workflow_runs_workflow_type_started_at_idx; Type: INDEX; Schema: public; Owner: -

CREATE INDEX workflow_runs_workflow_type_started_at_idx ON public.workflow_runs USING btree (workflow_type, started_at DESC);

-- Name: receipt_email receipt_email_charge_id_fkey; Type: FK CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.receipt_email
    ADD CONSTRAINT receipt_email_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES maou.recurring_charge(id);

-- Name: renewal_alert renewal_alert_charge_id_fkey; Type: FK CONSTRAINT; Schema: maou; Owner: -

ALTER TABLE ONLY maou.renewal_alert
    ADD CONSTRAINT renewal_alert_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES maou.recurring_charge(id);

-- Name: activities activities_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: agent_memory agent_memory_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.agent_memory
    ADD CONSTRAINT agent_memory_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: chat_history chat_history_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_history
    ADD CONSTRAINT chat_history_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: chat_tool_calls chat_tool_calls_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_tool_calls
    ADD CONSTRAINT chat_tool_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: connector_calls connector_calls_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.connector_calls
    ADD CONSTRAINT connector_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: connector_calls connector_calls_workflow_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.connector_calls
    ADD CONSTRAINT connector_calls_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_runs(run_id);

-- Name: interactions interactions_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.interactions
    ADD CONSTRAINT interactions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: knowledge_chunks knowledge_chunks_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_chunks
    ADD CONSTRAINT knowledge_chunks_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.knowledge_content(content_id) ON DELETE CASCADE;

-- Name: knowledge_injection_log knowledge_injection_log_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_injection_log
    ADD CONSTRAINT knowledge_injection_log_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: knowledge_injection_log knowledge_injection_log_workflow_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.knowledge_injection_log
    ADD CONSTRAINT knowledge_injection_log_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_runs(run_id);

-- Name: llm_calls llm_calls_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.llm_calls
    ADD CONSTRAINT llm_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);

-- Name: llm_calls llm_calls_workflow_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.llm_calls
    ADD CONSTRAINT llm_calls_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_runs(run_id);

-- Name: pending_prs pending_prs_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pending_prs
    ADD CONSTRAINT pending_prs_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES public.interactions(id);

-- Name: todoist_notes todoist_notes_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_notes
    ADD CONSTRAINT todoist_notes_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.todoist_tasks(id);

-- Name: todoist_projects todoist_projects_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_projects
    ADD CONSTRAINT todoist_projects_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.todoist_projects(id);

-- Name: todoist_tasks todoist_tasks_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_tasks
    ADD CONSTRAINT todoist_tasks_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.todoist_tasks(id);

-- Name: todoist_tasks todoist_tasks_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.todoist_tasks
    ADD CONSTRAINT todoist_tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.todoist_projects(id);

-- Name: workflow_runs workflow_runs_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.workflow_runs
    ADD CONSTRAINT workflow_runs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id);


-- =====================================================================
-- Public: infrastructure registry (dynamic hosts + provisioning)
-- =====================================================================

CREATE TABLE public.infra (
    id                   uuid DEFAULT gen_random_uuid() NOT NULL,
    slug                 text NOT NULL,
    name                 text NOT NULL,
    kind                 text DEFAULT 'ssh_host' NOT NULL,   -- ssh_host | swarm | docker | k8s
    host                 text,
    ssh_user             text,
    ssh_port             integer DEFAULT 22 NOT NULL,
    ssh_key_ref          text,                                -- path to private key on the core host
    docker_context       text,
    hosts_aegis          boolean DEFAULT false NOT NULL,      -- the entry that runs AEGIS itself (System monitoring)
    setup_files          jsonb DEFAULT '[]'::jsonb NOT NULL,  -- [{path, content, mode}] pushed on provision
    setup_command        text,                                -- optional command run after files are written
    status               text DEFAULT 'unprovisioned' NOT NULL, -- unprovisioned | provisioning | ready | error
    last_provisioned_at  timestamp with time zone,
    last_error           text,
    metadata             jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at           timestamp with time zone DEFAULT now() NOT NULL,
    updated_at           timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.infra ADD CONSTRAINT infra_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.infra ADD CONSTRAINT infra_slug_key UNIQUE (slug);
CREATE INDEX infra_hosts_aegis_idx ON public.infra (hosts_aegis) WHERE hosts_aegis;

-- Optional link: a resource (esp. a repository) can belong to an infra entry.
ALTER TABLE public.resources ADD COLUMN infra_id uuid;
ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_infra_id_fkey FOREIGN KEY (infra_id) REFERENCES public.infra(id) ON DELETE SET NULL;
CREATE INDEX resources_infra_id_idx ON public.resources (infra_id) WHERE infra_id IS NOT NULL;
